"""Jake-style LaTeX resume renderer.

The final resume is generated deterministically from the (optimized) Resume
JSON by injecting data into a fixed, validated LaTeX template — the LLM never
freely generates the document. Sections are only rendered when data exists.
"""

import logging

from .escape import escape_latex, escape_url_display, sanitize_url

logger = logging.getLogger(__name__)

RENDERER_VERSION = "v1"

# Fixed, validated Jake-style template. Placeholders are replaced by the
# renderer; no user content ever lands in the template body unescaped.
_TEMPLATE = r"""%-------------------------------------------------------------------------------
% Jake-style resume — generated by skillsaarthi (renderer %RENDERER_VERSION%)
%-------------------------------------------------------------------------------
\documentclass[11pt,a4paper]{article}

\usepackage[letterpaper, margin=0.7in, top=0.6in, bottom=0.6in]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{enumitem}
\usepackage{parskip}
\usepackage{xcolor}
\usepackage[hidelinks]{hyperref}
\usepackage{titlesec}

\definecolor{sectioncolor}{HTML}{0A2540}

\pagestyle{empty}
\setlist[itemize]{nosep,leftmargin=1.1em,topsep=2pt}
\titlespacing*{\section}{0pt}{*1.4}{*0.4}
\titleformat{\section}
  {\color{sectioncolor}\normalfont\scshape\bfseries\large}
  {}{0em}{}[\titlerule]

\begin{document}
\begin{center}
  {\LARGE\bfseries %NAME%}\\[4pt]
  %CONTACT%
\end{center}

%SECTIONS%
\end{document}
"""


def _section(title, body):
    return "\\section{%s}\n%s" % (escape_latex(title), body)


def _bullets(items):
    if not items:
        return ""
    lines = "\n".join("  \\item %s" % escape_latex(item) for item in items)
    return "\\begin{itemize}\n%s\n\\end{itemize}\n" % lines


def _contact_line(resume):
    personal = resume.get("personal") or {}
    items = []

    email = (personal.get("email") or "").strip()
    if email:
        url = sanitize_url("mailto:" + email)
        items.append("\\href{%s}{%s}" % (url, escape_latex(email)))

    phone = (personal.get("phone") or "").strip()
    if phone:
        items.append(escape_latex(phone))

    location = (personal.get("location") or "").strip()
    if location:
        items.append(escape_latex(location))

    for key, label in (
        ("linkedin", "LinkedIn"),
        ("github", "GitHub"),
        ("portfolio", "Portfolio"),
    ):
        url = sanitize_url(personal.get(key) or "")
        if url:
            display = (personal.get(key) or "").strip().replace("https://", "").replace("http://", "")
            items.append("\\href{%s}{%s}" % (url, escape_url_display(display or label)))

    return " $\\cdot$ ".join(items) if items else "\\textnormal{Contact information missing}"


def _render_summary(resume):
    summary = (resume.get("summary") or "").strip()
    if not summary:
        return ""
    return escape_latex(summary) + "\n"


def _render_education(resume):
    blocks = []
    for edu in resume.get("education", []):
        lines = []
        degree = (edu.get("degree") or "").strip()
        field = (edu.get("field") or "").strip()
        institution = (edu.get("institution") or "").strip()
        dates = _date_range(edu.get("start_date"), edu.get("end_date"))

        title_parts = [part for part in (degree, field) if part]
        left = " \\textbullet{} ".join(title_parts) or "Education"
        if institution:
            left = "%s, %s" % (institution, left)
        lines.append("\\textbf{%s} \\hfill \\textbf{%s}" % (escape_latex(left), escape_latex(dates)))

        details = []
        gpa = (edu.get("gpa") or "").strip()
        if gpa:
            details.append("GPA: %s" % escape_latex(gpa))
        bullets = _bullets(edu.get("bullets", []))
        if details:
            lines.append("  " + " $\\cdot$ ".join(details) + "\\\\")
        blocks.append("\n".join(lines))
        if bullets:
            blocks.append(bullets.rstrip("\n"))
    return "\n".join(blocks) + "\n"


def _render_experience(resume):
    blocks = []
    for exp in resume.get("experience", []):
        lines = []
        title = (exp.get("title") or "").strip()
        company = (exp.get("company") or "").strip()
        location = (exp.get("location") or "").strip()
        dates = _date_range(exp.get("start_date"), exp.get("end_date"))

        left = title or "Experience"
        if company:
            left = "%s, %s" % (left, company)
        lines.append("\\textbf{%s} \\hfill \\textbf{%s}" % (escape_latex(left), escape_latex(dates)))

        if location and location not in left:
            lines.append("\\textit{%s}" % escape_latex(location))

        tech = exp.get("technologies", [])
        if tech:
            lines.append("\\textit{Technologies: %s}" % escape_latex(", ".join(tech)))

        block = "\n".join(lines)
        bullets = _bullets(exp.get("bullets", []))
        if bullets:
            block += "\n" + bullets.rstrip("\n")
        blocks.append(block)
    return "\n".join(blocks) + "\n"


def _render_projects(resume):
    blocks = []
    for project in resume.get("projects", []):
        lines = []
        name = (project.get("name") or "").strip() or "Project"
        link = sanitize_url(project.get("link") or "")
        heading = "\\textbf{%s}" % escape_latex(name)
        if link:
            display = (project.get("link") or "").strip().replace("https://", "").replace("http://", "")
            heading += " \\href{%s}{%s}" % (link, escape_url_display(display))
        lines.append(heading)

        tech = project.get("technologies", [])
        if tech:
            lines.append("\\textit{Technologies: %s}" % escape_latex(", ".join(tech)))

        description = (project.get("description") or "").strip()
        block = "\n".join(lines)
        if description:
            block += "\n" + escape_latex(description)
        bullets = _bullets(project.get("bullets", []))
        if bullets:
            block += "\n" + bullets.rstrip("\n")
        blocks.append(block)
    return "\n".join(blocks) + "\n"


def _render_skills(resume):
    skills = resume.get("skills") or {}
    rows = []
    for category in ("languages", "frameworks", "libraries", "databases", "tools", "cloud", "other"):
        items = skills.get(category) or []
        names = []
        for item in items:
            if isinstance(item, dict):
                names.append(item.get("name"))
            elif isinstance(item, str):
                names.append(item)
        names = [n for n in names if n]
        if not names:
            continue
        label = category.replace("_", " ").title()
        rows.append("\\textbf{%s:} %s\\\\" % (escape_latex(label), escape_latex(", ".join(names))))
    return "\n".join(rows) + "\n"


def _render_certifications(resume):
    lines = []
    for cert in resume.get("certifications", []):
        name = (cert.get("name") or "").strip()
        issuer = (cert.get("issuer") or "").strip()
        date = (cert.get("date") or "").strip()
        parts = [part for part in (name, issuer) if part]
        left = " \\textbullet{} ".join(parts) or "Certification"
        lines.append("\\textbf{%s} \\hfill %s" % (escape_latex(left), escape_latex(date)))
    return "\n".join(lines) + "\n"


def _date_range(start, end):
    start = (start or "").strip()
    end = (end or "").strip()
    if not start and not end:
        return ""
    if start and end:
        return "%s -- %s" % (escape_latex(start), escape_latex(end))
    if start:
        return escape_latex(start)
    return escape_latex(end)


def render_resume(resume):
    """Render a Resume JSON dict into complete Jake-style LaTeX source."""
    resume = resume or {}
    sections = []

    summary = _render_summary(resume)
    if summary:
        sections.append(_section("Summary", summary))

    education = _render_education(resume)
    if education.strip():
        sections.append(_section("Education", education))

    experience = _render_experience(resume)
    if experience.strip():
        sections.append(_section("Experience", experience))

    projects = _render_projects(resume)
    if projects.strip():
        sections.append(_section("Projects", projects))

    skills = _render_skills(resume)
    if skills.strip():
        sections.append(_section("Technical Skills", skills))

    certifications = _render_certifications(resume)
    if certifications.strip():
        sections.append(_section("Certifications", certifications))

    achievements = resume.get("achievements", [])
    if achievements:
        sections.append(_section("Achievements", _bullets(achievements)))

    extracurriculars = resume.get("extracurriculars", [])
    if extracurriculars:
        sections.append(_section("Extracurricular Activities", _bullets(extracurriculars)))

    name = (resume.get("personal") or {}).get("name") or "Your Resume"
    contact = _contact_line(resume)

    tex = _TEMPLATE
    tex = tex.replace("%RENDERER_VERSION%", RENDERER_VERSION)
    tex = tex.replace("%NAME%", escape_latex(name))
    tex = tex.replace("%CONTACT%", contact)
    tex = tex.replace("%SECTIONS%", "\n".join(sections))
    return tex
